---
# tasks file for ansible-role-tinyproxy

- name: install packages
  tags: system
  ansible.builtin.package:
    name: ["tftpd-hpa"]
    state: present
    update_cache: yes

- name: Template a file to tftpd-hpa
  ansible.builtin.template:
    src: tftpd-hpa.j2
    dest: '/etc/default/tftpd-hpa'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: yes
  notify:
    - tftpd-hpa_reload_systemd

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ tftp_server_path }}"
    owner: "{{ tftp_server_user }}"
    group: "{{ tftp_server_group }}"
    mode: "{{ tftp_server_mode }}"

